name: keyboard_actions_plus
description: Now you can add features to the Android / iOS keyboard in a very simple way.
version: 5.0.0
repository: https://github.com/mdddj/flutter_keyboard_actions

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
